image: gitpod/workspace-full:latest

tasks:
  - name: Android SDK + Java 17 + Gradle Wrapper + Build
    init: |
      # 1) Java 17
      sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
      java -version

      # 2) Android SDK command-line tools in $ANDROID_SDK_ROOT
      export ANDROID_SDK_ROOT="$HOME/android-sdk"
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
      cd "$ANDROID_SDK_ROOT"
      curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      unzip -q cmdline-tools.zip -d cmdline-tools
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
      rm -f cmdline-tools.zip

      # 3) PATH for sdkmanager, platform-tools
      export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"

      # 4) Accept licenses and install required packages (API 34)
      yes | sdkmanager --licenses
      yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # 5) Build with Gradle Wrapper (generate if missing, then use ./gradlew)
      cd "$GITPOD_REPO_ROOT/ActivityStatusCompanion"
      if [ ! -f gradlew ]; then
        curl -s https://get.sdkman.io | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.10.2
        gradle wrapper --gradle-version 8.10.2
      fi
      chmod +x ./gradlew
      ./gradlew assembleDebug

    command: |
      cd "$GITPOD_REPO_ROOT/ActivityStatusCompanion"
      ./gradlew assembleDebug